language: node_js
node_js:
  - '14.15.1'
cache:
  yarn:true

before_install:
  - npm install -g yarn
  - yarn upgrade
install:
  - yarn install

script:
  - yarn build

branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: ${GITHUB_TOKEN}
  keep_history: false
  on:
    branch: master    